baseURL = "https://post.lilpilot.co/"
languageCode = "zh-cn"
title = "Postcard"
theme = "PaperMod"

[params]
defaultTheme = "light"
disableThemeToggle = true
showtoc = false
tocopen = false

[params.profileMode]
enabled = true
title = "Postcard"
imageUrl = "https://post.lilpilot.co/logo.jpg"
imageWidth = 120
imageHeight = 120
imageTitle = "lilpilot"

[[params.profileMode.buttons]]
name = "Posts"
url = "posts"

[[params.profileMode.buttons]]
name = "Tags"
url = "tags"